### PR TITLE
Change modeling of provision activity.

### LINKED ISSUE #225: Change in modeling of bf:Publication/Distribution/Manufacture/Production
**Type of change**
Change to existing mapping

**Example RDF records**
Please provide URIs or RDF of the `bf:Instance`. If providing RDF, Turtle is preferred.
https://api.development.sinopia.io/resource/d65b8846-2a6d-48c6-baed-ec4386a2e95a

**Resource template**
Which resource template does this apply to? In which Sinopia environment (development, stage, production)?
development: pcc:bf2:Monograph:Instance

**Expected MARC**
What MARC did you expect to receive?

008/15-17 onc
264 #1 London : Aristolochia, [2022]

**Expected mapping logic**
Please describe the logic of the mapping.

Using bf:Publication as example but same for other subclasses of bf:ProvisionActivity
bf:provisionActivity [a bf:Publication ;
        bf:place [lookup to MARC country codes] maps to 008/15-17
                      [lookup to FAST Geographic] maps to 651 #7 $a Ontario $z London $2 fast $0 <uri>
        bf:date <2022> (literal; edtf) maps to 008 06 = s
                                                     008 07-10 = 2022
        bflc:simplePlace <London> (literal) maps to 264 #1 $a London    (REPEATABLE)
        bflc:simpleAgent <Aristolochia> (literal) maps to 264 #1 $b Aristolochia (REPEATABLE)
        bflc:simpleDate (not datatyped) <[2022]> (literal) maps to 264 #1 $c [2022]
The full 264 should appear as: 
264 #1 $a London : $b Aristolochia, $c [2022]

This is a change being made to mapping by the Library of Congress. They are in the process of coding it.
Sinopia does not yet have the country codes, but according to Steven they should be in next week

### PR DESCRIPTION
**Pull request by justinlittman**
closes #225

## How was this change tested?
Unit

### CODE REVIEW

**Comment by justinlittman** [comment]
image

**Review by jermnelson — APPROVED** [review]

**Comment by NancyL** [comment]
So to be clear on what we accomplished with # 235. We now have the new model for bflc simpleplace, simplepublisher (etc.), simpledate in place that convert to MARC in the 264; + bf:date which converts to MARC in the 008 + a lookup for bf:place, but we do not yet have the lookup available to the country code. Is it set up to convert that country code when it's in place or does that still have to be coded?

**Comment by justinlittman** [comment]
It is set to convert that country code (in theory -- of course we'll want to test).

**Comment by NancyL** [comment]
cool. I still haven't got it yet from QA

**Pull request merged**
